"""empty message

Revision ID: 9fc6bc34caf4
Revises: 4ab82ce27be6
Create Date: 2016-07-14 11:52:08.441533

"""

# revision identifiers, used by Alembic.
revision = '9fc6bc34caf4'
down_revision = '4ab82ce27be6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'title')
    ### end Alembic commands ###
